# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_schema.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x11grpc_schema.proto\x12\x04grpc\"\x1b\n\x03Sum\x12\t\n\x01\x61\x18\x01 \x01(\x03\x12\t\n\x01\x62\x18\x02 \x01(\x03\"\x18\n\x0bSumResponse\x12\t\n\x01\x63\x18\x01 \x01(\x03\x32;\n\x04gRPC\x12\x33\n\x11GetServerResponse\x12\t.grpc.Sum\x1a\x11.grpc.SumResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, 'grpc_schema_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _SUM._serialized_start = 27
    _SUM._serialized_end = 54
    _SUMRESPONSE._serialized_start = 56
    _SUMRESPONSE._serialized_end = 80
    _GRPC._serialized_start = 82
    _GRPC._serialized_end = 141
# @@protoc_insertion_point(module_scope)
